### ISSUE TITLE
threshold > 75

### ISSUE THREAD

**Issue by djmannion** [arokem/yoon2009-schizophrenia-bulletin#1]
Hi Ariel,

Thanks very much for making this available.

I have noticed that participant 10454 has a threshold of "87.1". The paper says that those with a threshold > 75 had it set to 75, and this seems to have been applied to (aspects of) this data given that I would expect to see more > 75 if it hadn't been.

Can you please confirm that this value should be changed to 75?

Thanks.

**Comment by arokem** [comment]
Yes - that's probably right.  I think this does it: https://github.com/arokem/yoon2009-schizophrenia-bulletin/commit/60d1e05eaf7d6685fdefa0adf9b500a3d301fdf9

**Comment by djmannion** [comment]
Great - thanks for confirming.
